Repository vianneynara/kuenyawz-api, pull requests merged in 2024-11, with the labels that each got.

#78 Loop incrementer should've been incremented by one instead of two
  src/main/java/dev/realtards/kuenyawz/services/ProductCsvImportServiceImpl.java
Labels: bug

#99 Paginate products
  src/main/java/dev/realtards/kuenyawz/boostrappers/DatabaseBootstrapper.java
  src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java
  src/main/java/dev/realtards/kuenyawz/repositories/ProductRepository.java
  src/main/java/dev/realtards/kuenyawz/services/ProductCsvServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/ProductService.java
  src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/VariantService.java
  src/test/java/dev/realtards/kuenyawz/controllers/ProductControllerIT.java
  src/test/java/dev/realtards/kuenyawz/repositories/ProductRepositoryTest.java
  src/test/java/dev/realtards/kuenyawz/services/ProductServiceImplTest.java
Labels: enhancement

#122 Fix variant post dto not being validated properly during product creation
  src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPostDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/product/VariantPostDto.java
Labels: bug

#128 Create recommender endpoint and mock example
  src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java
  src/main/java/dev/realtards/kuenyawz/controllers/RecommenderController.java
  src/main/java/dev/realtards/kuenyawz/repositories/ProductSpecification.java
  src/main/java/dev/realtards/kuenyawz/services/RecommenderService.java
  src/main/java/dev/realtards/kuenyawz/services/RecommenderServiceImpl.java
Labels: enhancement

#137 Fix inconsistent enum value and case-insensitive handling for patching product
  src/main/java/dev/realtards/kuenyawz/dtos/product/ProductPatchDto.java
  src/main/java/dev/realtards/kuenyawz/entities/Product.java
  src/main/java/dev/realtards/kuenyawz/services/ProductServiceImpl.java
Labels: bug

#146 Feature/143 use phone number for primary username in jwt
  src/main/java/dev/realtards/kuenyawz/boostrappers/DatabaseBootstrapper.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/AccountUserDetailsService.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/ApplicationConfiguration.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/JwtAuthenticationFilter.java
  src/main/java/dev/realtards/kuenyawz/dtos/account/AccountPatchDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/account/AccountPutDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/account/AccountRegistrationDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/account/AccountSecureDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/account/PrivilegeUpdateDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/auth/AuthRequestDto.java
  src/main/java/dev/realtards/kuenyawz/entities/Account.java
  src/main/java/dev/realtards/kuenyawz/repositories/AccountRepository.java
  src/main/java/dev/realtards/kuenyawz/services/AccountService.java
  src/main/java/dev/realtards/kuenyawz/services/AccountServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/AuthServiceImpl.java
  src/test/java/dev/realtards/kuenyawz/repositories/AccountRepositoryTest.java
  src/test/java/dev/realtards/kuenyawz/services/AccountServiceImplTest.java
Labels: enhancement

#145 Feature/cart item base entity
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemPatchDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemPostDto.java
  src/main/java/dev/realtards/kuenyawz/repositories/CartItemRepository.java
Labels: enhancement

#147 Initialize cart item base entity and service interface
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemPatchDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/cartItem/CartItemPostDto.java
  src/main/java/dev/realtards/kuenyawz/repositories/CartItemRepository.java
Labels: enhancement

#150 Initialize OTP endpoint without WhatsApp
  .env.example
  src/main/java/dev/realtards/kuenyawz/advice/GlobalExceptionsHandler.java
  src/main/java/dev/realtards/kuenyawz/configurations/ApplicationProperties.java
  src/main/java/dev/realtards/kuenyawz/configurations/DatabaseConfig.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/JWTAuthenticationFilter.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java
  src/main/java/dev/realtards/kuenyawz/controllers/AuthController.java
  src/main/java/dev/realtards/kuenyawz/controllers/IndexController.java
  src/main/java/dev/realtards/kuenyawz/dtos/auth/OtpRequestDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/auth/OtpVerifyDto.java
  src/main/java/dev/realtards/kuenyawz/entities/OTP.java
  src/main/java/dev/realtards/kuenyawz/repositories/OTPRepository.java
  src/main/java/dev/realtards/kuenyawz/services/AuthServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/ImageStorageServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/JWTService.java
  src/main/java/dev/realtards/kuenyawz/services/JWTServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/OTPService.java
  src/main/java/dev/realtards/kuenyawz/services/OTPServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/RefreshTokenServiceImpl.java
  src/test/java/dev/realtards/kuenyawz/repositories/ProductRepositoryTest.java
Labels: enhancement, security

#163 Extracted tokens to http only cookies
  src/main/java/dev/realtards/kuenyawz/controllers/AuthController.java
Labels: security

#166 Integrate Fonnte Whatsapp OTP
  .env.example
  pom.xml
  src/main/java/dev/realtards/kuenyawz/configurations/ApplicationProperties.java
  src/main/java/dev/realtards/kuenyawz/dtos/fonnte/SendMessageDto.java
  src/main/java/dev/realtards/kuenyawz/services/OTPServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/WhatsappApiService.java
  src/main/java/dev/realtards/kuenyawz/services/WhatsappApiServiceImpl.java
Labels: enhancement, security

#169 Change jwt auth filter to check for access token from header and cookie
  src/main/java/dev/realtards/kuenyawz/advice/JwtExceptionsHandler.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/JWTAuthenticationFilter.java
  src/main/java/dev/realtards/kuenyawz/controllers/AuthController.java
  src/main/java/dev/realtards/kuenyawz/exceptions/InvalidRefreshTokenException.java
Labels: security

#171 Configure swagger with HTTP-only and allow all requests to /api/docs
  src/main/java/dev/realtards/kuenyawz/configurations/OpenAPIConfig.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java
  src/main/java/dev/realtards/kuenyawz/controllers/AccountController.java
  src/main/java/dev/realtards/kuenyawz/controllers/AuthController.java
  src/main/java/dev/realtards/kuenyawz/controllers/ProductController.java
  src/main/java/dev/realtards/kuenyawz/controllers/ProductImageController.java
Labels: configuration

#180 Verify otp to return 200 and 409
  src/main/java/dev/realtards/kuenyawz/services/entity/AccountService.java
  src/main/java/dev/realtards/kuenyawz/services/entity/AccountServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/entity/OTPServiceImpl.java
Labels: bug

#183 Use numeric as default otp can be set on properties
  src/main/java/dev/realtards/kuenyawz/configurations/ApplicationProperties.java
  src/main/java/dev/realtards/kuenyawz/configurations/StringToOTPTypeConverter.java
  src/main/java/dev/realtards/kuenyawz/services/entity/OTPService.java
  src/main/java/dev/realtards/kuenyawz/services/entity/OTPServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#185 Create custom schedule base entity service and controller
  src/main/java/dev/realtards/kuenyawz/configurations/ApplicationProperties.java
  src/main/java/dev/realtards/kuenyawz/configurations/OpenAPIConfig.java
  src/main/java/dev/realtards/kuenyawz/configurations/security/SecurityConfig.java
  src/main/java/dev/realtards/kuenyawz/controllers/ClosedDateController.java
  src/main/java/dev/realtards/kuenyawz/dtos/closeddate/ClosedDateDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/closeddate/ClosedDatePatchDto.java
  src/main/java/dev/realtards/kuenyawz/dtos/closeddate/ClosedDatePostDto.java
  src/main/java/dev/realtards/kuenyawz/entities/ClosedDate.java
  src/main/java/dev/realtards/kuenyawz/exceptions/InvalidPasswordException.java
  src/main/java/dev/realtards/kuenyawz/mapper/ClosedDateMapper.java
  src/main/java/dev/realtards/kuenyawz/repositories/ClosedDateRepository.java
  src/main/java/dev/realtards/kuenyawz/services/entity/ClosedDateService.java
  src/main/java/dev/realtards/kuenyawz/services/entity/ClosedDateServiceImpl.java
  src/main/java/dev/realtards/kuenyawz/services/logic/AuthService.java
Labels: enhancement

#191 Allow empty string on CartItemPostDto's note field validation
  src/main/java/dev/kons/kuenyawz/dtos/cartItem/CartItemPostDto.java
Labels: enhancement, quality of life

#192 Initialize Purchase, PurchaseItem, and Transaction with its DTOs
  src/main/java/dev/kons/kuenyawz/advice/GlobalExceptionsHandler.java
  src/main/java/dev/kons/kuenyawz/controllers/CartController.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/PurchaseDto.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/PurchaseItemDto.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/PurchaseItemPostDto.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/PurchasePatchDto.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/PurchasePostDto.java
  src/main/java/dev/kons/kuenyawz/dtos/purchase/TransactionDto.java
  src/main/java/dev/kons/kuenyawz/entities/Account.java
  src/main/java/dev/kons/kuenyawz/entities/Auditables.java
  src/main/java/dev/kons/kuenyawz/entities/CartItem.java
  src/main/java/dev/kons/kuenyawz/entities/ClosedDate.java
  src/main/java/dev/kons/kuenyawz/entities/Coordinate.java
  src/main/java/dev/kons/kuenyawz/entities/OTP.java
  src/main/java/dev/kons/kuenyawz/entities/Order.java
  src/main/java/dev/kons/kuenyawz/entities/OrderItem.java
  src/main/java/dev/kons/kuenyawz/entities/ProductImage.java
  src/main/java/dev/kons/kuenyawz/entities/Purchase.java
  src/main/java/dev/kons/kuenyawz/entities/PurchaseItem.java
  src/main/java/dev/kons/kuenyawz/entities/RefreshToken.java
  src/main/java/dev/kons/kuenyawz/entities/SoftDeleteAuditables.java
  src/main/java/dev/kons/kuenyawz/entities/Transaction.java
  src/main/java/dev/kons/kuenyawz/entities/Transactions.java
  src/main/java/dev/kons/kuenyawz/entities/Variant.java
  src/main/java/dev/kons/kuenyawz/services/entity/PurchaseService.java
Labels: enhancement

#197 Add images to cart item's product DTO
  src/main/java/dev/kons/kuenyawz/services/entity/CartItemServiceImpl.java
Labels: bug, enhancement

#200 Elaborate on cart items patch flow
  src/main/java/dev/kons/kuenyawz/controllers/CartController.java
  src/main/java/dev/kons/kuenyawz/dtos/cartItem/CartItemPatchDto.java
  src/main/java/dev/kons/kuenyawz/services/entity/CartItemServiceImpl.java
Labels: bug, documentation, enhancement

#202 Fix comparators and reset quantity if patch's variant is inconsistent
  src/main/java/dev/kons/kuenyawz/services/entity/CartItemServiceImpl.java
Labels: bug, enhancement, quality of life

#209 Sets the seeded products' availability to true by default
  src/main/java/dev/kons/kuenyawz/services/logic/ProductCsvServiceImpl.java
Labels: enhancement, quality of life
